version: '3.8'

services:
  nginx:
    image: nginx:1.21.1
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/
    depends_on:
      - php

  php:
    build: ./docker/php/
    volumes:
      - ./php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./src:/var/www/

  mysql:
    image: mysql:8.0.26
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=laravel_user
      - PMA_PASSWORD=laravel_pass
    depends_on:
      - mysql
    ports:
      - 8080:80

# version: '3.8'

# services:
#   nginx:
#     image: nginx:1.21.1
#     ports:
#       - "80:80"
#     volumes:
#       - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
#       - ./src:/var/www/
#     depends_on:
#       - php

#   php:
#     build: ./docker/php/
#     volumes:
#       - ./php-fpm.conf:/usr/local/etc/php-fpm.conf
#       - ./src:/var/www/
#     environment:
#       DB_CONNECTION: mysql
#       DB_HOST: rese-db.cs7ubfnzurvn.ap-northeast-1.rds.amazonaws.com
#       DB_PORT: 3306
#       DB_DATABASE: rese_db
#       DB_USERNAME: laravel_user
#       DB_PASSWORD: laravel_pass
#       # 以下はコメントアウトしています
#       # DB_HOST: mysql
#       # DB_PORT: 3306
#       # DB_DATABASE: laravel_db
#       # DB_USERNAME: laravel_user
#       # DB_PASSWORD: laravel_pass

#   # mysql:
#   #   image: mysql:8.0.26
#   #   environment:
#   #     MYSQL_ROOT_PASSWORD: root
#   #     MYSQL_DATABASE: laravel_db
#   #     MYSQL_USER: laravel_user
#   #     MYSQL_PASSWORD: laravel_pass
#   #   command: mysqld --default-authentication-plugin=mysql_native_password
#   #   volumes:
#   #     - ./docker/mysql/data:/var/lib/mysql
#   #     - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin
#     environment:
#       - PMA_ARBITRARY=1
#       - PMA_HOST: rese-db.cs7ubfnzurvn.ap-northeast-1.rds.amazonaws.com
#       - PMA_USER: laravel_user
#       - PMA_PASSWORD: laravel_pass
#     depends_on:
#       - php
#     ports:
#       - 8080:80
